### ISSUE TITLE
Servolux shutdown partially broken on Ruby 2.0.0

### ISSUE THREAD

**Issue by drbrain** [TwP/servolux#14]
In Ruby 2.0.0 a mutex cannot be locked in a signal handling context.  This prevents shutdown from working properly.

See also https://bugs.ruby-lang.org/issues/7917

**Comment by atombender** [comment]
I don't think it counts as a bug. You can use [mono_logger](https://github.com/steveklabnik/mono_logger) instead of `Logger` if you want to avoid this problem.
