### ISSUE TITLE
My object inherited from Servolux::Server terminated caused by Threaded's join (deadlock) running a period of time

### ISSUE THREAD

**Issue by dragonyy** [TwP/servolux#20]
Say that
class A < Servolux::Server

The execution path is
cmd => Thor => A.new.startup

At a random period of time (3 hours to 6 hours, or never happened, because the program is set to run one day only and will be sent a INT signal the next day), the following backtrace shows when some kind of exception occurs:

> /home/issdumrd/ruby20/lib/ruby/gems/2.0.0/gems/servolux-0.12.0/lib/threaded.rb:275:in `join': No live threads left. Deadlock? (fatal)
>     from /home/issdumrd/ruby20/lib/ruby/gems/2.0.0/gems/servolux-0.12.0/lib/servolux/threaded.rb:275:in `join'
>     from /home/issdumrd/ruby20/lib/ruby/gems/2.0.0/gemsems/servolux-0.12.0/lib/servolux/threaded.rb:104:in `join'
>     from /home/issdumrd/ruby20/lib/ruby/gems/2.0.0/gemsgems/servolux-0.12.0/lib/servolux/server.rb:192:in `startup'
>     from /home/issdumrd/ruby20/lib/ruby/gems/2.0.0/gems/idc-ranch3-0.0.5/lib/idc/ranch3/cli.rb:37:in `shepherd1'
>     from /home/issdumrd/ruby20/lib/ruby/gems/2.0.gems0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
>     from /home/issdumrdumrd/ruby20/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
>     from /home/issdumrd/ruby20/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
>     from /home/issdumrdd/ruby20/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
>     from /home/issdumrd/ruby20/lib/ruby/gems/2.0.0/gems/idc-ranch3-0.ranch30.5/bin/idc-ranch3:7:in `<top (required)>'
>     from /home/issdumrd/rubyy20/bin/idc-ranch3:23:in `load'
>     from /home/issdumrd/ruby20/bin/idc-ranch3:23:in `<main>'

The ruby VM version is ruby 2.0.0p451. 
And the main work in run method is to create some Concurrent::Future objects to finish their job (using concurrent-ruby gem, and in normal situation, those futures would not throw exception this way).

Maybe you can tell what happened according to the information above, or you can provide some ideas to avoid such an exception ?

Or I just need to change my ruby VM to Ruby 2.2.2 ?
Thanks in advance.

**Comment by TwP** [comment]
The `Servolux::Server` starts up and creates a new ruby thread that executes the `run` method at some interval. After that thread starts running, then the main ruby execution thread calls `join` on this new thread and waits for it to gracefully complete.

So this run thread is somehow deadlocking or getting itself into a state where it can no longer be run. It might be waiting on the main ruby thread again ... that would certainly cause a deadlock.

Are there any signals being sent to your application when this deadlock happens?

**Comment by TwP** [comment]
@dragonyy are you still having this problem? I'm cleaning up issues and wondering if this can be closed.

**Comment by dragonyy** [comment]
Dear sir, you can clean it up. Sorry I have not used this gem for a while.
